export const ADD_SERVICE = 'ADD_SERVICE';
export const EDIT_SERVICE = 'EDIT_SERVICE';
export const DELETE_SERVICE = 'DELETE_SERVICE';
export const SELECT_EDIT_SERVICE = 'SELECT_EDIT_SERVICE';
export const EDIT_SERVICE_ITEM = 'EDIT_SERVICE_ITEM';
export const VALIDATE_SERVICE_ITEM = 'VALIDATE_SERVICE_ITEM';
export const RESET_SERVICE_FORM = 'RESET_SERVICE_FORM';
export const EDIT_FILTER = 'EDIT_FILTER';